# Generated by Django 4.2.5 on 2023-09-28 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('music_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('music_name', models.CharField(max_length=120)),
                ('seconds', models.IntegerField()),
                ('singer', models.CharField(max_length=120)),
                ('pub_date', models.DateField()),
                ('url_picture', models.CharField(max_length=150)),
                ('music_rating', models.CharField(choices=[('10', 'Perfect'), ('9', 'Almost Perfect'), ('8', 'Wonderful'), ('7', 'Great'), ('6', 'Cool'), ('5', 'Ok'), ('4', 'Bad'), ('3', 'Very Bad'), ('2', 'Trash'), ('1', 'The wost thing in the entire world'), ('0', 'Default')], default='0', max_length=3)),
            ],
            options={
                'db_table': 'musicdb',
            },
        ),
        migrations.CreateModel(
            name='FindMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.music')),
            ],
        ),
    ]
