# Generated by Django 4.2.5 on 2023-10-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='url_picture',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
